import type { CEFRLevel } from "./level-manager";

// --- Type Definitions ---

export interface LessonStep {
  type: "listen" | "speak" | "speak-cloze" | "tip" | "choose" | "reorder" | "dictation";
  phrase: string;           // Persian phrase
  romanization: string;     // Romanized
  translation: string;      // Japanese translation
  tipText?: string;         // Pronunciation hint (Japanese)
  clozeWord?: string;       // Word to hide in cloze mode
  praiseText?: string;      // Persian praise text
  choices?: string[];       // "choose": 4 Japanese choices
  correctChoiceIndex?: number; // "choose": correct answer index
  words?: string[];         // "reorder": shuffled Persian words
}

export interface Lesson {
  id: string;
  title: string;            // Japanese title
  titlePersian: string;     // Persian title
  level: CEFRLevel;
  steps: LessonStep[];
}

// --- Lesson Content ---

export const GUIDED_LESSONS: Lesson[] = [
  // ═══════════════════════ A1 ═══════════════════════

  {
    id: "a1-greetings",
    title: "挨拶をしよう",
    titlePersian: "سلام کردن",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "سلام",
        romanization: "salaam",
        translation: "こんにちは",
        tipText: "最も基本的な挨拶です。どんな場面でも使えます。",
      },
      {
        type: "listen",
        phrase: "سلام",
        romanization: "salaam",
        translation: "こんにちは",
      },
      {
        type: "speak",
        phrase: "سلام",
        romanization: "salaam",
        translation: "こんにちは",
        praiseText: "آفرین!",
      },
      {
        type: "tip",
        phrase: "حالت چطوره؟",
        romanization: "haalet chetore?",
        translation: "元気？",
        tipText: "元気？と聞くカジュアルな表現です。親しい相手に使います。",
      },
      {
        type: "listen",
        phrase: "حالت چطوره؟",
        romanization: "haalet chetore?",
        translation: "元気？",
      },
      {
        type: "speak",
        phrase: "حالت چطوره؟",
        romanization: "haalet chetore?",
        translation: "元気？",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "خوبم ممنون",
        romanization: "khoobam mersi",
        translation: "元気だよ、ありがとう",
      },
      {
        type: "speak",
        phrase: "خوبم ممنون",
        romanization: "khoobam mersi",
        translation: "元気だよ、ありがとう",
        praiseText: "آفرین!",
      },
      {
        type: "speak-cloze",
        phrase: "سلام حالت چطوره؟",
        romanization: "salaam haalet chetore?",
        translation: "こんにちは、元気？",
        clozeWord: "چطوره",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "سلام! حالت چطوره؟ خوبم ممنون",
        romanization: "salaam! haalet chetore? khoobam mersi",
        translation: "こんにちは！元気？元気だよ、ありがとう",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-self-intro",
    title: "自己紹介",
    titlePersian: "معرفی خود",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "اسمم ... هست",
        romanization: "esmam ... hast",
        translation: "私の名前は...です",
        tipText: "名前を言う時の基本パターンです。...の部分に名前が入ります。",
      },
      {
        type: "listen",
        phrase: "اسمم مینا هست",
        romanization: "esmam Mina hast",
        translation: "私の名前はミーナです",
      },
      {
        type: "speak",
        phrase: "اسمم مینا هست",
        romanization: "esmam Mina hast",
        translation: "私の名前はミーナです",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "من ژاپنی هستم",
        romanization: "man zhaaponi hastam",
        translation: "私は日本人です",
      },
      {
        type: "speak",
        phrase: "من ژاپنی هستم",
        romanization: "man zhaaponi hastam",
        translation: "私は日本人です",
        praiseText: "عالی!",
      },
      {
        type: "tip",
        phrase: "از آشنایی‌تون خوشبختم",
        romanization: "az aashnaayitun khoshbakhtam",
        translation: "お会いできて嬉しいです",
        tipText: "お会いできて嬉しいです、という初対面の挨拶です。",
      },
      {
        type: "listen",
        phrase: "از آشنایی‌تون خوشبختم",
        romanization: "az aashnaayitun khoshbakhtam",
        translation: "お会いできて嬉しいです",
      },
      {
        type: "speak",
        phrase: "از آشنایی‌تون خوشبختم",
        romanization: "az aashnaayitun khoshbakhtam",
        translation: "お会いできて嬉しいです",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "من ژاپنی هستم",
        romanization: "man zhaaponi hastam",
        translation: "私は日本人です",
        clozeWord: "ژاپنی",
        praiseText: "آفرین!",
      },
      {
        type: "speak",
        phrase: "سلام اسمم مینا هست من ژاپنی هستم",
        romanization: "salaam esmam Mina hast man zhaaponi hastam",
        translation: "こんにちは、私の名前はミーナです。日本人です",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-numbers-shopping",
    title: "数字と買い物",
    titlePersian: "اعداد و خرید",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "یک دو سه",
        romanization: "yek do se",
        translation: "1 2 3",
        tipText: "ペルシア語の数字は日常会話で頻繁に使います。まず1-3から覚えましょう。",
      },
      {
        type: "listen",
        phrase: "یک دو سه",
        romanization: "yek do se",
        translation: "1 2 3",
      },
      {
        type: "speak",
        phrase: "یک دو سه",
        romanization: "yek do se",
        translation: "1 2 3",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "چند تا؟",
        romanization: "chand taa?",
        translation: "いくつ？",
      },
      {
        type: "speak",
        phrase: "چند تا؟",
        romanization: "chand taa?",
        translation: "いくつ？",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "قیمتش چقدره؟",
        romanization: "gheymatesh cheqadre?",
        translation: "これはいくらですか？",
      },
      {
        type: "speak",
        phrase: "قیمتش چقدره؟",
        romanization: "gheymatesh cheqadre?",
        translation: "これはいくらですか？",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "قیمتش چقدره؟",
        romanization: "gheymatesh cheqadre?",
        translation: "これはいくらですか？",
        clozeWord: "چقدره",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "سه تا لطفاً",
        romanization: "se taa lotfan",
        translation: "3つください",
      },
      {
        type: "speak",
        phrase: "سه تا لطفاً",
        romanization: "se taa lotfan",
        translation: "3つください",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-thanks",
    title: "ありがとう・ごめん",
    titlePersian: "تشکر و عذرخواهی",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "ممنون",
        romanization: "mersi",
        translation: "ありがとう",
        tipText: "フランス語由来の「ありがとう」です。日常で一番よく使います。",
      },
      {
        type: "listen",
        phrase: "ممنون",
        romanization: "mersi",
        translation: "ありがとう",
      },
      {
        type: "speak",
        phrase: "ممنون",
        romanization: "mersi",
        translation: "ありがとう",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "خیلی ممنون",
        romanization: "kheyli mersi",
        translation: "本当にありがとう",
      },
      {
        type: "speak",
        phrase: "خیلی ممنون",
        romanization: "kheyli mersi",
        translation: "本当にありがとう",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "ببخشید",
        romanization: "bebakhshid",
        translation: "すみません / ごめんなさい",
      },
      {
        type: "speak",
        phrase: "ببخشید",
        romanization: "bebakhshid",
        translation: "すみません / ごめんなさい",
        praiseText: "خیلی خوب!",
      },
      {
        type: "listen",
        phrase: "خواهش می‌کنم",
        romanization: "khaahesh mikonam",
        translation: "どういたしまして",
      },
      {
        type: "speak",
        phrase: "خواهش می‌کنم",
        romanization: "khaahesh mikonam",
        translation: "どういたしまして",
        praiseText: "آفرین!",
      },
      {
        type: "speak-cloze",
        phrase: "خیلی ممنون خواهش می‌کنم",
        romanization: "kheyli mersi khaahesh mikonam",
        translation: "本当にありがとう — どういたしまして",
        clozeWord: "خواهش",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-family",
    title: "家族の話",
    titlePersian: "خانواده",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "مادر",
        romanization: "maadar",
        translation: "お母さん",
        tipText: "お母さんという意味です。ここでは家族の呼び方を覚えましょう。",
      },
      {
        type: "listen",
        phrase: "این مادرمه",
        romanization: "in maadare man-e",
        translation: "これは私のお母さんです",
      },
      {
        type: "speak",
        phrase: "این مادرمه",
        romanization: "in maadare man-e",
        translation: "これは私のお母さんです",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "پدرم مهندسه",
        romanization: "pedaram mohandese",
        translation: "父はエンジニアです",
      },
      {
        type: "speak",
        phrase: "پدرم مهندسه",
        romanization: "pedaram mohandese",
        translation: "父はエンジニアです",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "خواهر",
        romanization: "khaahar",
        translation: "姉妹",
        choices: ["兄弟", "姉妹", "お母さん", "お父さん"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "یه خواهر و یه برادر دارم",
        romanization: "ye khaahar o ye baraadar daaram",
        translation: "姉妹が1人と兄弟が1人います",
      },
      {
        type: "reorder",
        phrase: "یه خواهر و یه برادر دارم",
        romanization: "ye khaahar o ye baraadar daaram",
        translation: "姉妹が1人と兄弟が1人います",
        words: ["دارم", "یه", "برادر", "و", "خواهر", "یه"],
      },
      {
        type: "dictation",
        phrase: "مادر",
        romanization: "maadar",
        translation: "お母さん",
      },
      {
        type: "speak",
        phrase: "خانواده‌ام بزرگه",
        romanization: "khaanavaade-am bozorge",
        translation: "私の家族は大きいです",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-food",
    title: "食べ物",
    titlePersian: "غذا",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "غذا",
        romanization: "ghazaa",
        translation: "食べ物",
        tipText: "食べ物全般を指す言葉です。",
      },
      {
        type: "listen",
        phrase: "نون و پنیر",
        romanization: "nun o panir",
        translation: "パンとチーズ",
      },
      {
        type: "speak",
        phrase: "نون و پنیر",
        romanization: "nun o panir",
        translation: "パンとチーズ",
        praiseText: "آفرین!",
      },
      {
        type: "choose",
        phrase: "آب",
        romanization: "aab",
        translation: "水",
        choices: ["お茶", "水", "牛乳", "ジュース"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "میوه دوست داری؟",
        romanization: "mive dust daari?",
        translation: "果物は好き？",
      },
      {
        type: "speak",
        phrase: "آره میوه خیلی دوست دارم",
        romanization: "aare mive kheyli dust daaram",
        translation: "うん、果物が大好き",
        praiseText: "عالی!",
      },
      {
        type: "reorder",
        phrase: "نون و پنیر می‌خوام",
        romanization: "nun o panir mikhaam",
        translation: "パンとチーズがほしい",
        words: ["می‌خوام", "پنیر", "و", "نون"],
      },
      {
        type: "dictation",
        phrase: "نون",
        romanization: "nun",
        translation: "パン",
      },
      {
        type: "speak-cloze",
        phrase: "میوه دوست دارم",
        romanization: "mive dust daaram",
        translation: "果物が好きです",
        clozeWord: "میوه",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "گشنمه غذا می‌خوام",
        romanization: "goshneme ghazaa mikhaam",
        translation: "お腹空いた、ごはんがほしい",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-colors",
    title: "色",
    titlePersian: "رنگ‌ها",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "قرمز",
        romanization: "ghermez",
        translation: "赤",
        tipText: "赤色です。色の名前は買い物でも役立ちます。",
      },
      {
        type: "listen",
        phrase: "این قرمزه",
        romanization: "in ghermeze",
        translation: "これは赤です",
      },
      {
        type: "speak",
        phrase: "این قرمزه",
        romanization: "in ghermeze",
        translation: "これは赤です",
        praiseText: "آفرین!",
      },
      {
        type: "choose",
        phrase: "آبی",
        romanization: "aabi",
        translation: "青",
        choices: ["赤", "緑", "青", "黄色"],
        correctChoiceIndex: 2,
      },
      {
        type: "listen",
        phrase: "سبز یا آبی؟",
        romanization: "sabz yaa aabi?",
        translation: "緑か青？",
      },
      {
        type: "speak",
        phrase: "آبی رو بیشتر دوست دارم",
        romanization: "aabi ro bishtar dust daaram",
        translation: "青のほうが好き",
        praiseText: "عالی!",
      },
      {
        type: "reorder",
        phrase: "رنگ مورد علاقم سبزه",
        romanization: "range mowrede alaaghame sabze",
        translation: "好きな色は緑です",
        words: ["سبزه", "علاقم", "مورد", "رنگ"],
      },
      {
        type: "dictation",
        phrase: "سفید",
        romanization: "sefid",
        translation: "白",
      },
      {
        type: "speak-cloze",
        phrase: "این قرمزه اون آبیه",
        romanization: "in ghermeze un aabiye",
        translation: "これは赤、あれは青",
        clozeWord: "آبیه",
        praiseText: "خیلی خوب!",
      },
    ],
  },

  {
    id: "a1-daily",
    title: "日常のフレーズ",
    titlePersian: "عبارت‌های روزمره",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "بله",
        romanization: "bale",
        translation: "はい",
        tipText: "丁寧な「はい」とカジュアルな「うん」があります。場面で使い分けましょう。",
      },
      {
        type: "listen",
        phrase: "بله ممنون",
        romanization: "bale mersi",
        translation: "はい、ありがとう",
      },
      {
        type: "speak",
        phrase: "بله ممنون",
        romanization: "bale mersi",
        translation: "はい、ありがとう",
        praiseText: "آفرین!",
      },
      {
        type: "choose",
        phrase: "نه",
        romanization: "na",
        translation: "いいえ",
        choices: ["はい", "いいえ", "ありがとう", "すみません"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "خداحافظ",
        romanization: "khodaahafez",
        translation: "さようなら",
      },
      {
        type: "speak",
        phrase: "خداحافظ",
        romanization: "khodaahafez",
        translation: "さようなら",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "لطفاً صبر کنید",
        romanization: "lotfan sabr konid",
        translation: "少々お待ちください",
      },
      {
        type: "reorder",
        phrase: "لطفاً صبر کنید",
        romanization: "lotfan sabr konid",
        translation: "少々お待ちください",
        words: ["کنید", "صبر", "لطفاً"],
      },
      {
        type: "dictation",
        phrase: "بله",
        romanization: "bale",
        translation: "はい",
      },
      {
        type: "speak",
        phrase: "خداحافظ تا بعد",
        romanization: "khodaahafez taa ba'd",
        translation: "さようなら、またね",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-body",
    title: "体の部位",
    titlePersian: "اعضای بدن",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "سر",
        romanization: "sar",
        translation: "頭",
        tipText: "頭という意味です。体調が悪い時にも使うので覚えましょう。",
      },
      {
        type: "listen",
        phrase: "سرم درد می‌کنه",
        romanization: "saram dard mikone",
        translation: "頭が痛い",
      },
      {
        type: "speak",
        phrase: "سرم درد می‌کنه",
        romanization: "saram dard mikone",
        translation: "頭が痛い",
        praiseText: "آفرین!",
      },
      {
        type: "choose",
        phrase: "دست",
        romanization: "dast",
        translation: "手",
        choices: ["足", "手", "目", "頭"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "چشمات قشنگه",
        romanization: "cheshmaat ghashange",
        translation: "あなたの目はきれいです",
      },
      {
        type: "speak",
        phrase: "چشمات قشنگه",
        romanization: "cheshmaat ghashange",
        translation: "あなたの目はきれいです",
        praiseText: "عالی!",
      },
      {
        type: "reorder",
        phrase: "سرم درد می‌کنه",
        romanization: "saram dard mikone",
        translation: "頭が痛い",
        words: ["می‌کنه", "درد", "سرم"],
      },
      {
        type: "dictation",
        phrase: "چشم",
        romanization: "cheshm",
        translation: "目",
      },
      {
        type: "speak-cloze",
        phrase: "دستم درد می‌کنه",
        romanization: "dastam dard mikone",
        translation: "手が痛い",
        clozeWord: "دستم",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "پام درد می‌کنه نمی‌تونم راه برم",
        romanization: "paam dard mikone nemitoonam raah beram",
        translation: "足が痛くて歩けない",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a1-weather",
    title: "天気",
    titlePersian: "آب و هوا",
    level: "A1",
    steps: [
      {
        type: "tip",
        phrase: "هوا خوبه",
        romanization: "havaa khoobe",
        translation: "天気がいい",
        tipText: "天気がいい、という意味です。天気の話は挨拶の定番です。",
      },
      {
        type: "listen",
        phrase: "امروز هوا خوبه",
        romanization: "emruz havaa khoobe",
        translation: "今日は天気がいい",
      },
      {
        type: "speak",
        phrase: "امروز هوا خوبه",
        romanization: "emruz havaa khoobe",
        translation: "今日は天気がいい",
        praiseText: "آفرین!",
      },
      {
        type: "choose",
        phrase: "بارون میاد",
        romanization: "baarun miaad",
        translation: "雨が降っている",
        choices: ["雪が降っている", "天気がいい", "雨が降っている", "暑い"],
        correctChoiceIndex: 2,
      },
      {
        type: "listen",
        phrase: "فردا بارون میاد",
        romanization: "fardaa baarun miaad",
        translation: "明日は雨が降る",
      },
      {
        type: "speak",
        phrase: "فردا بارون میاد",
        romanization: "fardaa baarun miaad",
        translation: "明日は雨が降る",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "خیلی سرده",
        romanization: "kheyli sarde",
        translation: "とても寒い",
      },
      {
        type: "reorder",
        phrase: "امروز هوا خیلی گرمه",
        romanization: "emruz havaa kheyli garme",
        translation: "今日はとても暑い",
        words: ["گرمه", "خیلی", "هوا", "امروز"],
      },
      {
        type: "dictation",
        phrase: "بارون",
        romanization: "baarun",
        translation: "雨",
      },
      {
        type: "speak",
        phrase: "هوا سرده لباس گرم بپوش",
        romanization: "havaa sarde lebaase garm bepush",
        translation: "寒いよ、暖かい服を着て",
        praiseText: "عالی بود!",
      },
    ],
  },

  // ═══════════════════════ A2 ═══════════════════════

  {
    id: "a2-cafe-order",
    title: "カフェで注文する",
    titlePersian: "سفارش در کافه",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "یه قهوه لطفاً",
        romanization: "ye qahve lotfan",
        translation: "コーヒーを1つお願いします",
        tipText: "「1つの」のカジュアルな言い方です。注文する時によく使います。",
      },
      {
        type: "listen",
        phrase: "سلام یه قهوه لطفاً",
        romanization: "salaam ye qahve lotfan",
        translation: "こんにちは、コーヒーを1つお願いします",
      },
      {
        type: "speak",
        phrase: "سلام یه قهوه لطفاً",
        romanization: "salaam ye qahve lotfan",
        translation: "こんにちは、コーヒーを1つお願いします",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "با شیر یا بدون شیر؟",
        romanization: "baa shir yaa bedune shir?",
        translation: "ミルクありですか、なしですか？",
      },
      {
        type: "speak",
        phrase: "با شیر لطفاً",
        romanization: "baa shir lotfan",
        translation: "ミルクありでお願いします",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "چیز دیگه‌ای می‌خواید؟",
        romanization: "chize digei mikhaaid?",
        translation: "他にご注文はありますか？",
      },
      {
        type: "speak",
        phrase: "یه کیک هم لطفاً",
        romanization: "ye keyk ham lotfan",
        translation: "ケーキも1つお願いします",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "یه قهوه با شیر لطفاً",
        romanization: "ye qahve baa shir lotfan",
        translation: "ミルク入りコーヒーを1つお願いします",
        clozeWord: "شیر",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "حساب لطفاً",
        romanization: "hesaab lotfan",
        translation: "お会計お願いします",
      },
      {
        type: "speak",
        phrase: "حساب لطفاً",
        romanization: "hesaab lotfan",
        translation: "お会計お願いします",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-directions",
    title: "道を聞く",
    titlePersian: "پرسیدن آدرس",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "ببخشید",
        romanization: "bebakhshid",
        translation: "すみません",
        tipText: "道を聞く時は「すみません」から始めましょう。",
      },
      {
        type: "listen",
        phrase: "ببخشید مترو کجاست؟",
        romanization: "bebakhshid metro kojaast?",
        translation: "すみません、地下鉄はどこですか？",
      },
      {
        type: "speak",
        phrase: "ببخشید مترو کجاست؟",
        romanization: "bebakhshid metro kojaast?",
        translation: "すみません、地下鉄はどこですか？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "مستقیم برید",
        romanization: "mostaghim berid",
        translation: "まっすぐ行ってください",
      },
      {
        type: "speak",
        phrase: "مستقیم برید",
        romanization: "mostaghim berid",
        translation: "まっすぐ行ってください",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "بپیچید سمت راست",
        romanization: "bepichid samte raast",
        translation: "右に曲がってください",
      },
      {
        type: "speak",
        phrase: "بپیچید سمت راست",
        romanization: "bepichid samte raast",
        translation: "右に曲がってください",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "ببخشید مترو کجاست؟",
        romanization: "bebakhshid metro kojaast?",
        translation: "すみません、地下鉄はどこですか？",
        clozeWord: "کجاست",
        praiseText: "آفرین!",
      },
      {
        type: "speak",
        phrase: "خیلی ممنون",
        romanization: "kheyli mersi",
        translation: "どうもありがとう",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-restaurant",
    title: "レストランで注文",
    titlePersian: "سفارش در رستوران",
    level: "A2",
    steps: [
      {
        type: "listen",
        phrase: "یه میز برای دو نفر لطفاً",
        romanization: "ye miz baraaye do nafar lotfan",
        translation: "2名のテーブルをお願いします",
      },
      {
        type: "speak",
        phrase: "یه میز برای دو نفر لطفاً",
        romanization: "ye miz baraaye do nafar lotfan",
        translation: "2名のテーブルをお願いします",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "منو رو ببینم",
        romanization: "menu ro bebinam",
        translation: "メニューを見せてください",
      },
      {
        type: "speak",
        phrase: "منو رو ببینم",
        romanization: "menu ro bebinam",
        translation: "メニューを見せてください",
        praiseText: "عالی!",
      },
      {
        type: "tip",
        phrase: "چلوکباب",
        romanization: "chelow kabaab",
        translation: "チェロケバブ（ご飯+ケバブ）",
        tipText: "イラン料理の代表格。ご飯とケバブのセットです。",
      },
      {
        type: "listen",
        phrase: "یه چلوکباب لطفاً",
        romanization: "ye chelow kabaab lotfan",
        translation: "チェロケバブを1つお願いします",
      },
      {
        type: "speak",
        phrase: "یه چلوکباب لطفاً",
        romanization: "ye chelow kabaab lotfan",
        translation: "チェロケバブを1つお願いします",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "یه میز برای دو نفر لطفاً",
        romanization: "ye miz baraaye do nafar lotfan",
        translation: "2名のテーブルをお願いします",
        clozeWord: "نفر",
        praiseText: "آفرین!",
      },
      {
        type: "speak",
        phrase: "حساب لطفاً خیلی ممنون",
        romanization: "hesaab lotfan kheyli mersi",
        translation: "お会計お願いします、ありがとうございます",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-time",
    title: "時間を聞く",
    titlePersian: "پرسیدن ساعت",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "ساعت چنده؟",
        romanization: "saa'at chande?",
        translation: "何時ですか？",
        tipText: "何時ですか？と聞く定番フレーズです。",
      },
      {
        type: "listen",
        phrase: "ساعت چنده؟",
        romanization: "saa'at chande?",
        translation: "何時ですか？",
      },
      {
        type: "speak",
        phrase: "ساعت چنده؟",
        romanization: "saa'at chande?",
        translation: "何時ですか？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "ساعت سه و نیم",
        romanization: "saa'at se o nim",
        translation: "3時半です",
      },
      {
        type: "speak",
        phrase: "ساعت سه و نیم",
        romanization: "saa'at se o nim",
        translation: "3時半です",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "کی می‌رسی؟",
        romanization: "key miresi?",
        translation: "いつ着きますか？",
      },
      {
        type: "speak",
        phrase: "کی می‌رسی؟",
        romanization: "key miresi?",
        translation: "いつ着きますか？",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "ساعت سه و نیم",
        romanization: "saa'at se o nim",
        translation: "3時半です",
        clozeWord: "نیم",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-clothes-shopping",
    title: "服を買う",
    titlePersian: "خرید لباس",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "این چقدره؟",
        romanization: "in cheqadre?",
        translation: "これはいくらですか？",
        tipText: "これいくらですか？と聞く買い物の定番フレーズです。",
      },
      {
        type: "listen",
        phrase: "این چقدره؟",
        romanization: "in cheqadre?",
        translation: "これはいくらですか？",
      },
      {
        type: "speak",
        phrase: "این چقدره؟",
        romanization: "in cheqadre?",
        translation: "これはいくらですか？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "سایز بزرگ‌تر دارید؟",
        romanization: "saayz bozorgtar daarid?",
        translation: "もっと大きいサイズはありますか？",
      },
      {
        type: "speak",
        phrase: "سایز بزرگ‌تر دارید؟",
        romanization: "saayz bozorgtar daarid?",
        translation: "もっと大きいサイズはありますか？",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "می‌تونم امتحانش کنم؟",
        romanization: "mitoonam emtehaanesh konam?",
        translation: "試着できますか？",
        choices: ["返品できますか？", "試着できますか？", "値下げできますか？", "他の色はありますか？"],
        correctChoiceIndex: 1,
      },
      {
        type: "reorder",
        phrase: "سایز بزرگ‌تر دارید؟",
        romanization: "saayz bozorgtar daarid?",
        translation: "もっと大きいサイズはありますか？",
        words: ["دارید؟", "بزرگ‌تر", "سایز"],
      },
      {
        type: "dictation",
        phrase: "این چقدره؟",
        romanization: "in cheqadre?",
        translation: "これはいくらですか？",
      },
      {
        type: "speak-cloze",
        phrase: "رنگ دیگه‌ای دارید؟",
        romanization: "range digei daarid?",
        translation: "他の色はありますか？",
        clozeWord: "رنگ",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "این رو می‌برم خیلی ممنون",
        romanization: "in ro mibaram kheyli mersi",
        translation: "これをもらいます、ありがとう",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-doctor",
    title: "医者に行く",
    titlePersian: "رفتن به دکتر",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "حالم خوب نیست",
        romanization: "haalam khoob nist",
        translation: "体調が悪い",
        tipText: "具合が悪い、と伝えるフレーズです。病院で最初に使います。",
      },
      {
        type: "listen",
        phrase: "حالم خوب نیست",
        romanization: "haalam khoob nist",
        translation: "体調が悪い",
      },
      {
        type: "speak",
        phrase: "حالم خوب نیست",
        romanization: "haalam khoob nist",
        translation: "体調が悪い",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "سرم درد می‌کنه",
        romanization: "saram dard mikone",
        translation: "頭が痛いです",
      },
      {
        type: "speak",
        phrase: "سرم درد می‌کنه",
        romanization: "saram dard mikone",
        translation: "頭が痛いです",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "تب دارم",
        romanization: "tab daaram",
        translation: "熱があります",
        choices: ["咳が出ます", "熱があります", "お腹が痛い", "鼻水が出ます"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "از کی اینجوری شدی؟",
        romanization: "az key injuri shodi?",
        translation: "いつからこうなりましたか？",
      },
      {
        type: "reorder",
        phrase: "از دیروز سرم درد می‌کنه",
        romanization: "az diruz saram dard mikone",
        translation: "昨日から頭が痛いです",
        words: ["می‌کنه", "درد", "سرم", "دیروز", "از"],
      },
      {
        type: "dictation",
        phrase: "حالم خوب نیست",
        romanization: "haalam khoob nist",
        translation: "体調が悪い",
      },
      {
        type: "speak",
        phrase: "این دارو رو روزی سه بار بخورید",
        romanization: "in daaru ro ruzi se baar bokhorid",
        translation: "この薬を1日3回飲んでください",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-weekend",
    title: "週末の予定",
    titlePersian: "برنامه آخر هفته",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "آخر هفته چیکار می‌کنی؟",
        romanization: "aakhare hafte chikaar mikoni?",
        translation: "週末は何するの？",
        tipText: "週末何するの？と予定を聞く定番フレーズです。",
      },
      {
        type: "listen",
        phrase: "آخر هفته چیکار می‌کنی؟",
        romanization: "aakhare hafte chikaar mikoni?",
        translation: "週末は何するの？",
      },
      {
        type: "speak",
        phrase: "آخر هفته چیکار می‌کنی؟",
        romanization: "aakhare hafte chikaar mikoni?",
        translation: "週末は何するの？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "می‌خوام برم سینما",
        romanization: "mikhaam beram sinemaa",
        translation: "映画館に行きたい",
      },
      {
        type: "speak",
        phrase: "می‌خوام برم سینما",
        romanization: "mikhaam beram sinemaa",
        translation: "映画館に行きたい",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "بیا با هم بریم",
        romanization: "biaa baa ham berim",
        translation: "一緒に行こうよ",
        choices: ["一人で行くよ", "行きたくない", "一緒に行こうよ", "もう行ったよ"],
        correctChoiceIndex: 2,
      },
      {
        type: "reorder",
        phrase: "آخر هفته چیکار می‌کنی؟",
        romanization: "aakhare hafte chikaar mikoni?",
        translation: "週末は何するの？",
        words: ["می‌کنی؟", "چیکار", "هفته", "آخر"],
      },
      {
        type: "dictation",
        phrase: "سینما",
        romanization: "sinemaa",
        translation: "映画館",
      },
      {
        type: "speak-cloze",
        phrase: "می‌خوام برم سینما",
        romanization: "mikhaam beram sinemaa",
        translation: "映画館に行きたい",
        clozeWord: "سینما",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "باشه ساعت چند قرار بذاریم؟",
        romanization: "baashe saa'at chand gharaar bezaarim?",
        translation: "OK、何時に待ち合わせしようか？",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "a2-phone",
    title: "電話する",
    titlePersian: "تلفن زدن",
    level: "A2",
    steps: [
      {
        type: "tip",
        phrase: "الو",
        romanization: "alo",
        translation: "もしもし",
        tipText: "電話に出る時の第一声です。日本語の「もしもし」に相当します。",
      },
      {
        type: "listen",
        phrase: "الو سلام",
        romanization: "alo salaam",
        translation: "もしもし、こんにちは",
      },
      {
        type: "speak",
        phrase: "الو سلام",
        romanization: "alo salaam",
        translation: "もしもし、こんにちは",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "می‌تونم با آقای احمدی صحبت کنم؟",
        romanization: "mitoonam baa aaghaaye Ahmadi sohbat konam?",
        translation: "アフマディさんとお話できますか？",
      },
      {
        type: "speak",
        phrase: "می‌تونم با آقای احمدی صحبت کنم؟",
        romanization: "mitoonam baa aaghaaye Ahmadi sohbat konam?",
        translation: "アフマディさんとお話できますか？",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "یه لحظه صبر کنید",
        romanization: "ye lahze sabr konid",
        translation: "少々お待ちください",
        choices: ["切ってください", "少々お待ちください", "かけ直してください", "間違い電話です"],
        correctChoiceIndex: 1,
      },
      {
        type: "reorder",
        phrase: "می‌تونم با آقای احمدی صحبت کنم؟",
        romanization: "mitoonam baa aaghaaye Ahmadi sohbat konam?",
        translation: "アフマディさんとお話できますか？",
        words: ["کنم؟", "صحبت", "احمدی", "آقای", "با", "می‌تونم"],
      },
      {
        type: "dictation",
        phrase: "الو سلام",
        romanization: "alo salaam",
        translation: "もしもし、こんにちは",
      },
      {
        type: "speak-cloze",
        phrase: "بعداً بهتون زنگ می‌زنم",
        romanization: "ba'dan behetun zang mizanam",
        translation: "後で電話します",
        clozeWord: "زنگ",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "خداحافظ خوشحال شدم صحبت کردیم",
        romanization: "khodaahafez khoshhaal shodam sohbat kardim",
        translation: "さようなら、お話できてよかったです",
        praiseText: "عالی بود!",
      },
    ],
  },

  // ═══════════════════════ B1 ═══════════════════════

  {
    id: "b1-travel-plans",
    title: "旅行の計画",
    titlePersian: "برنامه سفر",
    level: "B1",
    steps: [
      {
        type: "tip",
        phrase: "می‌خوام برم سفر",
        romanization: "mikhaam beram safar",
        translation: "旅行に行きたい",
        tipText: "〜したい、という意味です。日常会話で最もよく使う表現の一つです。",
      },
      {
        type: "listen",
        phrase: "می‌خوام تابستون برم اصفهان",
        romanization: "mikhaam taabestun beram esfahaan",
        translation: "夏にイスファハンに行きたい",
      },
      {
        type: "speak",
        phrase: "می‌خوام تابستون برم اصفهان",
        romanization: "mikhaam taabestun beram esfahaan",
        translation: "夏にイスファハンに行きたい",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "هتل رزرو کردی؟",
        romanization: "hotel rezerv kardi?",
        translation: "ホテルは予約した？",
      },
      {
        type: "speak",
        phrase: "هنوز نه باید رزرو کنم",
        romanization: "hanuz na baayad rezerv konam",
        translation: "まだ。予約しないと",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "چند روز می‌مونی؟",
        romanization: "chand ruz mimooni?",
        translation: "何日滞在するの？",
      },
      {
        type: "speak",
        phrase: "فکر کنم یه هفته",
        romanization: "fekr konam ye hafte",
        translation: "たぶん1週間",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "می‌خوام تابستون برم اصفهان",
        romanization: "mikhaam taabestun beram esfahaan",
        translation: "夏にイスファハンに行きたい",
        clozeWord: "تابستون",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-opinions",
    title: "意見を言う",
    titlePersian: "اظهار نظر",
    level: "B1",
    steps: [
      {
        type: "listen",
        phrase: "به نظر من",
        romanization: "be nazare man",
        translation: "私の意見では",
      },
      {
        type: "speak",
        phrase: "به نظر من",
        romanization: "be nazare man",
        translation: "私の意見では",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "به نظر من این فیلم خیلی خوب بود",
        romanization: "be nazare man in film kheyli khoob bud",
        translation: "この映画はとても良かったと思う",
      },
      {
        type: "speak",
        phrase: "به نظر من این فیلم خیلی خوب بود",
        romanization: "be nazare man in film kheyli khoob bud",
        translation: "この映画はとても良かったと思う",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "موافقم ولی فکر می‌کنم",
        romanization: "movaafegham vali fekr mikonam",
        translation: "賛成だけど、思うに...",
      },
      {
        type: "speak",
        phrase: "موافقم ولی فکر می‌کنم",
        romanization: "movaafegham vali fekr mikonam",
        translation: "賛成だけど、思うに...",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "به نظر من این فیلم خیلی خوب بود",
        romanization: "be nazare man in film kheyli khoob bud",
        translation: "この映画はとても良かったと思う",
        clozeWord: "فیلم",
        praiseText: "آفرین!",
      },
      {
        type: "speak",
        phrase: "من مخالفم چون فکر می‌کنم",
        romanization: "man mokhaalefam chon fekr mikonam",
        translation: "反対です、なぜなら思うに...",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-daily-routine",
    title: "日常を話す",
    titlePersian: "زندگی روزمره",
    level: "B1",
    steps: [
      {
        type: "listen",
        phrase: "صبح زود بیدار می‌شم",
        romanization: "sobh zud bidaar misham",
        translation: "朝早く起きます",
      },
      {
        type: "speak",
        phrase: "صبح زود بیدار می‌شم",
        romanization: "sobh zud bidaar misham",
        translation: "朝早く起きます",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "بعد از صبحانه می‌رم سر کار",
        romanization: "ba'd az sobhaane miram sare kaar",
        translation: "朝食後に仕事に行きます",
      },
      {
        type: "speak",
        phrase: "بعد از صبحانه می‌رم سر کار",
        romanization: "ba'd az sobhaane miram sare kaar",
        translation: "朝食後に仕事に行きます",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "عصرها ورزش می‌کنم",
        romanization: "asrhaa varzesh mikonam",
        translation: "午後は運動します",
      },
      {
        type: "speak",
        phrase: "عصرها ورزش می‌کنم",
        romanization: "asrhaa varzesh mikonam",
        translation: "午後は運動します",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "بعد از صبحانه می‌رم سر کار",
        romanization: "ba'd az sobhaane miram sare kaar",
        translation: "朝食後に仕事に行きます",
        clozeWord: "صبحانه",
        praiseText: "آفرین!",
      },
      {
        type: "speak",
        phrase: "شب‌ها کتاب می‌خونم و می‌خوابم",
        romanization: "shabhaa ketaab mikhoonam o mikhaanam",
        translation: "夜は本を読んで寝ます",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-work-talk",
    title: "仕事の話",
    titlePersian: "صحبت درباره کار",
    level: "B1",
    steps: [
      {
        type: "listen",
        phrase: "شغلت چیه؟",
        romanization: "shoghlat chie?",
        translation: "仕事は何ですか？",
      },
      {
        type: "speak",
        phrase: "شغلت چیه؟",
        romanization: "shoghlat chie?",
        translation: "仕事は何ですか？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "من مهندس نرم‌افزار هستم",
        romanization: "man mohandese narm-afzaar hastam",
        translation: "ソフトウェアエンジニアです",
      },
      {
        type: "speak",
        phrase: "من مهندس نرم‌افزار هستم",
        romanization: "man mohandese narm-afzaar hastam",
        translation: "ソフトウェアエンジニアです",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "از کارت راضی هستی؟",
        romanization: "az kaaret raazi hasti?",
        translation: "仕事に満足してる？",
      },
      {
        type: "speak",
        phrase: "آره خیلی دوستش دارم",
        romanization: "aare kheyli dustesh daaram",
        translation: "うん、すごく好きだよ",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "من مهندس نرم‌افزار هستم",
        romanization: "man mohandese narm-afzaar hastam",
        translation: "ソフトウェアエンジニアです",
        clozeWord: "مهندس",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-education",
    title: "教育の話",
    titlePersian: "تحصیلات",
    level: "B1",
    steps: [
      {
        type: "tip",
        phrase: "دانشگاه",
        romanization: "daaneshgaah",
        translation: "大学",
        tipText: "大学という意味です。教育に関する語彙を覚えましょう。",
      },
      {
        type: "listen",
        phrase: "کجا درس می‌خونی؟",
        romanization: "kojaa dars mikhooni?",
        translation: "どこで勉強してるの？",
      },
      {
        type: "speak",
        phrase: "دانشگاه تهران درس می‌خونم",
        romanization: "daaneshgaahe tehraan dars mikhoonam",
        translation: "テヘラン大学で勉強しています",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "رشته‌ات چیه؟",
        romanization: "reshte-at chie?",
        translation: "専攻は何ですか？",
      },
      {
        type: "speak",
        phrase: "رشته‌ام مهندسی کامپیوتره",
        romanization: "reshte-am mohandesi-ye kaampiutare",
        translation: "専攻はコンピューター工学です",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "فارغ‌التحصیل شدم",
        romanization: "faareghottahsil shodam",
        translation: "卒業しました",
        choices: ["入学しました", "退学しました", "卒業しました", "留年しました"],
        correctChoiceIndex: 2,
      },
      {
        type: "reorder",
        phrase: "رشته‌ام مهندسی کامپیوتره",
        romanization: "reshte-am mohandesi-ye kaampiutare",
        translation: "専攻はコンピューター工学です",
        words: ["کامپیوتره", "مهندسی", "رشته‌ام"],
      },
      {
        type: "dictation",
        phrase: "دانشگاه",
        romanization: "daaneshgaah",
        translation: "大学",
      },
      {
        type: "speak-cloze",
        phrase: "رشته‌ات چیه؟",
        romanization: "reshte-at chie?",
        translation: "専攻は何ですか？",
        clozeWord: "رشته‌ات",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "دوست دارم بعد از لیسانس فوق لیسانس بگیرم",
        romanization: "dust daaram ba'd az lisaans fowghe lisaans begiram",
        translation: "学部卒業後に修士号を取りたい",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-health",
    title: "健康の話",
    titlePersian: "سلامتی",
    level: "B1",
    steps: [
      {
        type: "tip",
        phrase: "ورزش می‌کنم",
        romanization: "varzesh mikonam",
        translation: "運動しています",
        tipText: "運動するという意味です。健康の話題は日常会話でよく出ます。",
      },
      {
        type: "listen",
        phrase: "هر روز ورزش می‌کنی؟",
        romanization: "har ruz varzesh mikoni?",
        translation: "毎日運動してる？",
      },
      {
        type: "speak",
        phrase: "آره هفته‌ای سه بار می‌رم باشگاه",
        romanization: "aare hafte-i se baar miram baashgaah",
        translation: "うん、週3回ジムに行ってるよ",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "رژیم غذایی داری؟",
        romanization: "rezhime ghazaayi daari?",
        translation: "食事制限してる？",
      },
      {
        type: "speak",
        phrase: "سعی می‌کنم سالم غذا بخورم",
        romanization: "sa'y mikonam saalem ghazaa bokhoram",
        translation: "健康的に食べるようにしてるよ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "سیگار نمی‌کشم",
        romanization: "sigaar nemikesham",
        translation: "タバコは吸いません",
        choices: ["タバコを吸います", "タバコは吸いません", "タバコをやめました", "タバコを買いたい"],
        correctChoiceIndex: 1,
      },
      {
        type: "reorder",
        phrase: "هر روز ورزش می‌کنم",
        romanization: "har ruz varzesh mikonam",
        translation: "毎日運動しています",
        words: ["می‌کنم", "ورزش", "روز", "هر"],
      },
      {
        type: "dictation",
        phrase: "ورزش می‌کنم",
        romanization: "varzesh mikonam",
        translation: "運動しています",
      },
      {
        type: "speak-cloze",
        phrase: "سعی می‌کنم سالم غذا بخورم",
        romanization: "sa'y mikonam saalem ghazaa bokhoram",
        translation: "健康的に食べるようにしてるよ",
        clozeWord: "سالم",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak",
        phrase: "خواب کافی خیلی مهمه برای سلامتی",
        romanization: "khvaabe kaafi kheyli moheme baraaye salaamati",
        translation: "十分な睡眠は健康にとても大事です",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-environment",
    title: "環境の話",
    titlePersian: "محیط زیست",
    level: "B1",
    steps: [
      {
        type: "tip",
        phrase: "آلودگی هوا",
        romanization: "aaludegi-ye havaa",
        translation: "大気汚染",
        tipText: "大気汚染のことです。テヘランでもよく話題になる環境問題の定番トピックです。",
      },
      {
        type: "listen",
        phrase: "آلودگی هوا تو تهران خیلی بده",
        romanization: "aaludegi-ye havaa tu tehraan kheyli bade",
        translation: "テヘランの大気汚染はとてもひどい",
      },
      {
        type: "speak",
        phrase: "آلودگی هوا تو تهران خیلی بده",
        romanization: "aaludegi-ye havaa tu tehraan kheyli bade",
        translation: "テヘランの大気汚染はとてもひどい",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "بازیافت خیلی مهمه برای محیط زیست",
        romanization: "baaziaaft kheyli moheme baraaye mohite zist",
        translation: "リサイクルは環境にとってとても大切だ",
      },
      {
        type: "speak",
        phrase: "بازیافت خیلی مهمه برای محیط زیست",
        romanization: "baaziaaft kheyli moheme baraaye mohite zist",
        translation: "リサイクルは環境にとってとても大切だ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "طبیعت",
        romanization: "tabi'at",
        translation: "自然",
        choices: ["環境汚染", "自然", "リサイクル", "ゴミ"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "باید از طبیعت محافظت کنیم",
        romanization: "baayad az tabi'at mohaafezt konim",
        translation: "自然を守るべきだ",
      },
      {
        type: "reorder",
        phrase: "بازیافت خیلی مهمه برای محیط زیست",
        romanization: "baaziaaft kheyli moheme baraaye mohite zist",
        translation: "リサイクルは環境にとってとても大切だ",
        words: ["زیست", "محیط", "برای", "مهمه", "خیلی", "بازیافت"],
      },
      {
        type: "dictation",
        phrase: "محیط زیست",
        romanization: "mohite zist",
        translation: "環境",
      },
      {
        type: "speak",
        phrase: "اگه همه با هم کمک کنیم می‌تونیم آلودگی رو کم کنیم",
        romanization: "age hame baa ham komak konim mitoonim aaludegi ro kam konim",
        translation: "みんなで協力すれば汚染を減らせる",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b1-movie-review",
    title: "映画レビュー",
    titlePersian: "نقد فیلم",
    level: "B1",
    steps: [
      {
        type: "tip",
        phrase: "ژانر",
        romanization: "zhaanr",
        translation: "ジャンル",
        tipText: "フランス語由来の言葉です。映画のジャンルについて話す時に使います。",
      },
      {
        type: "listen",
        phrase: "دیشب یه فیلم خیلی خوب دیدم",
        romanization: "dishab ye filme kheyli khoob didam",
        translation: "昨夜すごくいい映画を見た",
      },
      {
        type: "speak",
        phrase: "دیشب یه فیلم خیلی خوب دیدم",
        romanization: "dishab ye filme kheyli khoob didam",
        translation: "昨夜すごくいい映画を見た",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "بازیگرها عالی بودن مخصوصاً نقش اول",
        romanization: "baazigarha aali budan makhsusan naghshe avval",
        translation: "俳優たちが素晴らしかった、特に主役",
      },
      {
        type: "speak",
        phrase: "بازیگرها عالی بودن مخصوصاً نقش اول",
        romanization: "baazigarha aali budan makhsusan naghshe avval",
        translation: "俳優たちが素晴らしかった、特に主役",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "کارگردان",
        romanization: "kaargardaan",
        translation: "監督",
        choices: ["脚本家", "俳優", "監督", "プロデューサー"],
        correctChoiceIndex: 2,
      },
      {
        type: "listen",
        phrase: "فیلمنامه جالب بود ولی آخرش ضعیف بود",
        romanization: "filmnaame jaaleb bud vali aakheresh za'if bud",
        translation: "脚本は面白かったけど結末が弱かった",
      },
      {
        type: "reorder",
        phrase: "کارگردان این فیلم خیلی معروفه",
        romanization: "kaargardaane in film kheyli ma'rufe",
        translation: "この映画の監督はとても有名だ",
        words: ["معروفه", "خیلی", "فیلم", "این", "کارگردان"],
      },
      {
        type: "dictation",
        phrase: "بازیگر",
        romanization: "baazigaar",
        translation: "俳優",
      },
      {
        type: "speak",
        phrase: "از ده نمره بهش هشت می‌دم ارزش دیدن داره",
        romanization: "az dah nomre behesh hasht midam arzeshe didan daare",
        translation: "10点中8点をあげる、見る価値がある",
        praiseText: "عالی بود!",
      },
    ],
  },

  // ═══════════════════════ B2 ═══════════════════════

  {
    id: "b2-culture",
    title: "文化を比較する",
    titlePersian: "مقایسه فرهنگ‌ها",
    level: "B2",
    steps: [
      {
        type: "listen",
        phrase: "فرهنگ ایران و ژاپن شباهت‌های زیادی دارن",
        romanization: "farhange iraan o zhaapon shabaahat-haaye ziaadi daaran",
        translation: "イランと日本の文化には多くの類似点がある",
      },
      {
        type: "speak",
        phrase: "فرهنگ ایران و ژاپن شباهت‌های زیادی دارن",
        romanization: "farhange iraan o zhaapon shabaahat-haaye ziaadi daaran",
        translation: "イランと日本の文化には多くの類似点がある",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "مثلاً هر دو فرهنگ به احترام اهمیت می‌دن",
        romanization: "masalan har do farhang be ehteraam ahamiyat midan",
        translation: "例えば、両文化とも礼儀を重視する",
      },
      {
        type: "speak",
        phrase: "مثلاً هر دو فرهنگ به احترام اهمیت می‌دن",
        romanization: "masalan har do farhang be ehteraam ahamiyat midan",
        translation: "例えば、両文化とも礼儀を重視する",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "ولی تفاوت‌هایی هم هست",
        romanization: "vali tafaavot-haayee ham hast",
        translation: "でも違いもある",
      },
      {
        type: "speak",
        phrase: "ولی تفاوت‌هایی هم هست",
        romanization: "vali tafaavot-haayee ham hast",
        translation: "でも違いもある",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "فرهنگ ایران و ژاپن شباهت‌های زیادی دارن",
        romanization: "farhange iraan o zhaapon shabaahat-haaye ziaadi daaran",
        translation: "イランと日本の文化には多くの類似点がある",
        clozeWord: "شباهت‌های",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-future-dreams",
    title: "将来の夢を語る",
    titlePersian: "آرزوهای آینده",
    level: "B2",
    steps: [
      {
        type: "listen",
        phrase: "آرزوت برای آینده چیه؟",
        romanization: "aarezut baraaye aayande chie?",
        translation: "将来の夢は何ですか？",
      },
      {
        type: "speak",
        phrase: "آرزوت برای آینده چیه؟",
        romanization: "aarezut baraaye aayande chie?",
        translation: "将来の夢は何ですか？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "دوست دارم یه روز تو ایران زندگی کنم",
        romanization: "dust daaram ye ruz tu iraan zendegi konam",
        translation: "いつかイランに住みたい",
      },
      {
        type: "speak",
        phrase: "دوست دارم یه روز تو ایران زندگی کنم",
        romanization: "dust daaram ye ruz tu iraan zendegi konam",
        translation: "いつかイランに住みたい",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "امیدوارم بتونم این آرزو رو برآورده کنم",
        romanization: "omidvaaram betoonam in aarezu ro baraavarde konam",
        translation: "この夢を叶えられるといいな",
      },
      {
        type: "speak",
        phrase: "امیدوارم بتونم این آرزو رو برآورده کنم",
        romanization: "omidvaaram betoonam in aarezu ro baraavarde konam",
        translation: "この夢を叶えられるといいな",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "دوست دارم یه روز تو ایران زندگی کنم",
        romanization: "dust daaram ye ruz tu iraan zendegi konam",
        translation: "いつかイランに住みたい",
        clozeWord: "زندگی",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-debate",
    title: "議論する",
    titlePersian: "بحث و مناظره",
    level: "B2",
    steps: [
      {
        type: "listen",
        phrase: "از نظر من این موضوع پیچیده‌ست",
        romanization: "az nazare man in mowzu' pichidast",
        translation: "私の見解では、この問題は複雑だ",
      },
      {
        type: "speak",
        phrase: "از نظر من این موضوع پیچیده‌ست",
        romanization: "az nazare man in mowzu' pichidast",
        translation: "私の見解では、この問題は複雑だ",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "باید همه جوانب رو در نظر بگیریم",
        romanization: "baayad hame javaaneb ro dar nazar begirim",
        translation: "全ての側面を考慮すべきだ",
      },
      {
        type: "speak",
        phrase: "باید همه جوانب رو در نظر بگیریم",
        romanization: "baayad hame javaaneb ro dar nazar begirim",
        translation: "全ての側面を考慮すべきだ",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "با این حال معتقدم که",
        romanization: "baa in haal mo'taghedam ke",
        translation: "それでも私は...と信じている",
      },
      {
        type: "speak",
        phrase: "با این حال معتقدم که",
        romanization: "baa in haal mo'taghedam ke",
        translation: "それでも私は...と信じている",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "باید همه جوانب رو در نظر بگیریم",
        romanization: "baayad hame javaaneb ro dar nazar begirim",
        translation: "全ての側面を考慮すべきだ",
        clozeWord: "جوانب",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-news",
    title: "ニュースを討論",
    titlePersian: "بحث درباره اخبار",
    level: "B2",
    steps: [
      {
        type: "listen",
        phrase: "اخبار امروز رو دیدی؟",
        romanization: "akhbaare emruz ro didi?",
        translation: "今日のニュース見た？",
      },
      {
        type: "speak",
        phrase: "اخبار امروز رو دیدی؟",
        romanization: "akhbaare emruz ro didi?",
        translation: "今日のニュース見た？",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "آره یه خبر جالب بود درباره",
        romanization: "aare ye khabare jaaleb bud darbaare",
        translation: "うん、...についての面白いニュースがあった",
      },
      {
        type: "speak",
        phrase: "آره یه خبر جالب بود درباره",
        romanization: "aare ye khabare jaaleb bud darbaare",
        translation: "うん、...についての面白いニュースがあった",
        praiseText: "عالی!",
      },
      {
        type: "listen",
        phrase: "فکر می‌کنم تأثیر زیادی داشته باشه",
        romanization: "fekr mikonam ta'sire ziaadi daashte baashe",
        translation: "大きな影響があると思う",
      },
      {
        type: "speak",
        phrase: "فکر می‌کنم تأثیر زیادی داشته باشه",
        romanization: "fekr mikonam ta'sire ziaadi daashte baashe",
        translation: "大きな影響があると思う",
        praiseText: "خیلی خوب!",
      },
      {
        type: "speak-cloze",
        phrase: "فکر می‌کنم تأثیر زیادی داشته باشه",
        romanization: "fekr mikonam ta'sire ziaadi daashte baashe",
        translation: "大きな影響があると思う",
        clozeWord: "تأثیر",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-technology",
    title: "テクノロジー",
    titlePersian: "فناوری",
    level: "B2",
    steps: [
      {
        type: "tip",
        phrase: "هوش مصنوعی",
        romanization: "hushe masnu'i",
        translation: "人工知能",
        tipText: "人工知能（AI）のことです。テクノロジーの話題で頻出です。",
      },
      {
        type: "listen",
        phrase: "هوش مصنوعی خیلی پیشرفت کرده",
        romanization: "hushe masnu'i kheyli pishraft karde",
        translation: "AIはとても進歩した",
      },
      {
        type: "speak",
        phrase: "هوش مصنوعی خیلی پیشرفت کرده",
        romanization: "hushe masnu'i kheyli pishraft karde",
        translation: "AIはとても進歩した",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "اینترنت زندگی ما رو عوض کرده",
        romanization: "internet zendegiye maa ro avaz karde",
        translation: "インターネットは私たちの生活を変えた",
      },
      {
        type: "speak",
        phrase: "اینترنت زندگی ما رو عوض کرده",
        romanization: "internet zendegiye maa ro avaz karde",
        translation: "インターネットは私たちの生活を変えた",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "فضای مجازی",
        romanization: "fazaaye majaazi",
        translation: "ソーシャルメディア（仮想空間）",
        choices: ["人工知能", "インターネット", "ソーシャルメディア", "プログラミング"],
        correctChoiceIndex: 2,
      },
      {
        type: "listen",
        phrase: "فکر می‌کنی تکنولوژی آینده چجوری می‌شه؟",
        romanization: "fekr mikoni teknolozhi-ye aayande chejuri mishe?",
        translation: "未来のテクノロジーはどうなると思う？",
      },
      {
        type: "reorder",
        phrase: "هوش مصنوعی خیلی پیشرفت کرده",
        romanization: "hushe masnu'i kheyli pishraft karde",
        translation: "AIはとても進歩した",
        words: ["کرده", "پیشرفت", "خیلی", "مصنوعی", "هوش"],
      },
      {
        type: "dictation",
        phrase: "هوش مصنوعی",
        romanization: "hushe masnu'i",
        translation: "人工知能",
      },
      {
        type: "speak",
        phrase: "به نظرم تکنولوژی هم مزایا داره هم معایب",
        romanization: "be nazaram teknolozhi ham mazaayaa daare ham ma'aayeb",
        translation: "テクノロジーにはメリットもデメリットもあると思う",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-economics",
    title: "経済の話",
    titlePersian: "اقتصاد",
    level: "B2",
    steps: [
      {
        type: "tip",
        phrase: "تورم",
        romanization: "tavarrom",
        translation: "インフレーション",
        tipText: "インフレのことです。イランでは経済の話は日常の一部で、物価上昇は常に話題になります。",
      },
      {
        type: "listen",
        phrase: "نرخ تورم امسال خیلی بالا رفته",
        romanization: "nerkhe tavarrom emsaal kheyli baalaa rafte",
        translation: "今年のインフレ率はとても上がった",
      },
      {
        type: "speak",
        phrase: "نرخ تورم امسال خیلی بالا رفته",
        romanization: "nerkhe tavarrom emsaal kheyli baalaa rafte",
        translation: "今年のインフレ率はとても上がった",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "بازار بورس خیلی نوسان داره",
        romanization: "baazaare burs kheyli navasaan daare",
        translation: "株式市場はとても変動が大きい",
      },
      {
        type: "speak",
        phrase: "بازار بورس خیلی نوسان داره",
        romanization: "baazaare burs kheyli navasaan daare",
        translation: "株式市場はとても変動が大きい",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "سرمایه‌گذاری",
        romanization: "sarmaaye-gozaari",
        translation: "投資",
        choices: ["貯蓄", "投資", "借金", "輸出"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "قدرت خرید مردم کاهش پیدا کرده",
        romanization: "ghodrate kharide mardom kaahesh peydaa karde",
        translation: "人々の購買力が低下した",
      },
      {
        type: "reorder",
        phrase: "نرخ تورم امسال خیلی بالا رفته",
        romanization: "nerkhe tavarrom emsaal kheyli baalaa rafte",
        translation: "今年のインフレ率はとても上がった",
        words: ["رفته", "بالا", "خیلی", "امسال", "تورم", "نرخ"],
      },
      {
        type: "dictation",
        phrase: "بازار",
        romanization: "baazaar",
        translation: "市場",
      },
      {
        type: "speak",
        phrase: "دولت باید سیاست‌های اقتصادی مؤثرتری اتخاذ کنه",
        romanization: "dowlat baayad siaasathaa-ye eqtesaadi-ye mo'assartar-i ettekhaz kone",
        translation: "政府はより効果的な経済政策を採るべきだ",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-psychology",
    title: "心理学の話",
    titlePersian: "روان‌شناسی",
    level: "B2",
    steps: [
      {
        type: "tip",
        phrase: "استرس",
        romanization: "esteres",
        translation: "ストレス",
        tipText: "ストレスのことです。心理的な話題はイラン社会でも注目されています。",
      },
      {
        type: "listen",
        phrase: "استرس زیاد برای سلامت روان مضره",
        romanization: "esteres-e ziaad baraaye salaamate ravaan mozerre",
        translation: "過度なストレスは精神的健康に有害だ",
      },
      {
        type: "speak",
        phrase: "استرس زیاد برای سلامت روان مضره",
        romanization: "esteres-e ziaad baraaye salaamate ravaan mozerre",
        translation: "過度なストレスは精神的健康に有害だ",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "مدیریت احساسات یه مهارت مهمه",
        romanization: "modiriyate ehsaasaat ye mahaarat-e moheme",
        translation: "感情のコントロールは重要なスキルだ",
      },
      {
        type: "speak",
        phrase: "مدیریت احساسات یه مهارت مهمه",
        romanization: "modiriyate ehsaasaat ye mahaarat-e moheme",
        translation: "感情のコントロールは重要なスキルだ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "رفتار",
        romanization: "raftaar",
        translation: "行動",
        choices: ["感情", "行動", "思考", "記憶"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "رفتن پیش روان‌شناس هیچ عیبی نداره",
        romanization: "raftan pishe ravaanshenaas hich eybi nadaare",
        translation: "心理カウンセラーに行くことは全く恥ずかしくない",
      },
      {
        type: "reorder",
        phrase: "مدیریت احساسات یه مهارت مهمه",
        romanization: "modiriyate ehsaasaat ye mahaarat-e moheme",
        translation: "感情のコントロールは重要なスキルだ",
        words: ["مهمه", "مهارت", "یه", "احساسات", "مدیریت"],
      },
      {
        type: "dictation",
        phrase: "احساسات",
        romanization: "ehsaasaat",
        translation: "感情",
      },
      {
        type: "speak",
        phrase: "باید یاد بگیریم که با فشارهای روانی کنار بیایم",
        romanization: "baayad yaad begirim ke baa feshaarhaaye ravaani kenaar biaayim",
        translation: "精神的なプレッシャーと向き合うことを学ぶべきだ",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "b2-media",
    title: "メディアリテラシー",
    titlePersian: "سواد رسانه‌ای",
    level: "B2",
    steps: [
      {
        type: "tip",
        phrase: "رسانه",
        romanization: "resaane",
        translation: "メディア",
        tipText: "メディア・報道のことです。情報社会で欠かせない語彙です。",
      },
      {
        type: "listen",
        phrase: "خبر جعلی تو شبکه‌های اجتماعی خیلی پخش می‌شه",
        romanization: "khabare ja'li tu shabakehaa-ye ejtemaa'i kheyli pakhsh mishe",
        translation: "フェイクニュースはSNSでとても広まる",
      },
      {
        type: "speak",
        phrase: "خبر جعلی تو شبکه‌های اجتماعی خیلی پخش می‌شه",
        romanization: "khabare ja'li tu shabakehaa-ye ejtemaa'i kheyli pakhsh mishe",
        translation: "フェイクニュースはSNSでとても広まる",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "باید منبع خبر رو بررسی کنیم",
        romanization: "baayad manba'e khabar ro barresi konim",
        translation: "ニュースのソースを確認すべきだ",
      },
      {
        type: "speak",
        phrase: "باید منبع خبر رو بررسی کنیم",
        romanization: "baayad manba'e khabar ro barresi konim",
        translation: "ニュースのソースを確認すべきだ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "تبلیغات",
        romanization: "tablighaaat",
        translation: "広告",
        choices: ["ニュース", "広告", "記事", "放送"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "تبلیغات ممکنه ما رو گمراه کنه",
        romanization: "tablighaaat momkene maa ro gomraah kone",
        translation: "広告は私たちを惑わす可能性がある",
      },
      {
        type: "reorder",
        phrase: "باید منبع خبر رو بررسی کنیم",
        romanization: "baayad manba'e khabar ro barresi konim",
        translation: "ニュースのソースを確認すべきだ",
        words: ["کنیم", "بررسی", "رو", "خبر", "منبع", "باید"],
      },
      {
        type: "dictation",
        phrase: "خبر جعلی",
        romanization: "khabare ja'li",
        translation: "フェイクニュース",
      },
      {
        type: "speak",
        phrase: "سواد رسانه‌ای به ما کمک می‌کنه اطلاعات درست رو از نادرست تشخیص بدیم",
        romanization: "savaade resaane-i be maa komak mikone ettelaa'aate dorost ro az naadorost tashkhis bedim",
        translation: "メディアリテラシーは正しい情報と誤情報を見分ける助けになる",
        praiseText: "عالی بود!",
      },
    ],
  },

  // ═══════════════════════ C1 ═══════════════════════

  {
    id: "c1-academic-discussion",
    title: "学術的議論",
    titlePersian: "بحث آکادمیک",
    level: "C1",
    steps: [
      {
        type: "tip",
        phrase: "فرضیه",
        romanization: "farziye",
        translation: "仮説",
        tipText: "仮説のことです。学術論文や研究で使うアカデミックな議論の基本語彙です。",
      },
      {
        type: "listen",
        phrase: "این فرضیه بر اساس داده‌های تجربی قابل اثبات نیست",
        romanization: "in farziye bar asaase daadehaa-ye tajrobi ghaabele esbaat nist",
        translation: "この仮説は実証データに基づいて証明できない",
      },
      {
        type: "speak",
        phrase: "این فرضیه بر اساس داده‌های تجربی قابل اثبات نیست",
        romanization: "in farziye bar asaase daadehaa-ye tajrobi ghaabele esbaat nist",
        translation: "この仮説は実証データに基づいて証明できない",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "روش‌شناسی این پژوهش نیاز به بازنگری داره",
        romanization: "ravesh-shenaasi-ye in pazhuhesh niaaz be baazangari daare",
        translation: "この研究の方法論は見直しが必要だ",
      },
      {
        type: "speak",
        phrase: "روش‌شناسی این پژوهش نیاز به بازنگری داره",
        romanization: "ravesh-shenaasi-ye in pazhuhesh niaaz be baazangari daare",
        translation: "この研究の方法論は見直しが必要だ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "یافته‌ها",
        romanization: "yaaftehaa",
        translation: "研究結果",
        choices: ["仮説", "方法論", "研究結果", "参考文献"],
        correctChoiceIndex: 2,
      },
      {
        type: "listen",
        phrase: "یافته‌های این تحقیق با مطالعات قبلی در تناقض است",
        romanization: "yaaftehaa-ye in tahghigh baa motaale'aate ghabli dar tanaaghoz ast",
        translation: "この研究の結果は先行研究と矛盾している",
      },
      {
        type: "speak",
        phrase: "یافته‌های این تحقیق با مطالعات قبلی در تناقض است",
        romanization: "yaaftehaa-ye in tahghigh baa motaale'aate ghabli dar tanaaghoz ast",
        translation: "この研究の結果は先行研究と矛盾している",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "روش‌شناسی این پژوهش نیاز به بازنگری داره",
        romanization: "ravesh-shenaasi-ye in pazhuhesh niaaz be baazangari daare",
        translation: "この研究の方法論は見直しが必要だ",
        words: ["داره", "بازنگری", "به", "نیاز", "پژوهش", "این", "روش‌شناسی"],
      },
      {
        type: "dictation",
        phrase: "فرضیه",
        romanization: "farziye",
        translation: "仮説",
      },
      {
        type: "speak",
        phrase: "لازمه که چارچوب نظری پژوهش رو قبل از جمع‌آوری داده‌ها مشخص کنیم",
        romanization: "laazeme ke chaarchube nazari-ye pazhuhesh ro ghabl az jam'-aavari-ye daadehaa moshakhkhas konim",
        translation: "データ収集の前に研究の理論的枠組みを明確にする必要がある",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c1-politics",
    title: "政治討論",
    titlePersian: "بحث سیاسی",
    level: "C1",
    steps: [
      {
        type: "tip",
        phrase: "دموکراسی",
        romanization: "demokraasi",
        translation: "民主主義",
        tipText: "民主主義のことです。政治討論の基本語彙で、イランでも知識人の間で頻繁に議論されます。",
      },
      {
        type: "listen",
        phrase: "تحقق دموکراسی مستلزم مشارکت فعال شهروندان است",
        romanization: "tahagghoghe demokraasi mostalzeme moshaarekate fa''aale shahrvandaan ast",
        translation: "民主主義の実現には市民の積極的な参加が不可欠だ",
      },
      {
        type: "speak",
        phrase: "تحقق دموکراسی مستلزم مشارکت فعال شهروندان است",
        romanization: "tahagghoghe demokraasi mostalzeme moshaarekate fa''aale shahrvandaan ast",
        translation: "民主主義の実現には市民の積極的な参加が不可欠だ",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "حقوق بشر باید فارغ از ملاحظات سیاسی رعایت بشه",
        romanization: "hoghuughe bashar baayad faareghe az molaahezaate siaasi re'aayat beshe",
        translation: "人権は政治的考慮にかかわらず尊重されるべきだ",
      },
      {
        type: "speak",
        phrase: "حقوق بشر باید فارغ از ملاحظات سیاسی رعایت بشه",
        romanization: "hoghuughe bashar baayad faareghe az molaahezaate siaasi re'aayat beshe",
        translation: "人権は政治的考慮にかかわらず尊重されるべきだ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "سیاست خارجی",
        romanization: "siaasate khaareji",
        translation: "外交政策",
        choices: ["国内政策", "外交政策", "経済政策", "安全保障"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "تحریم‌ها تأثیر عمیقی بر اقتصاد و معیشت مردم گذاشته",
        romanization: "tahrimhaa ta'sire amighi bar eqtesaad o ma'ishate mardom gozaashte",
        translation: "制裁は経済と人々の生活に深い影響を与えた",
      },
      {
        type: "speak",
        phrase: "تحریم‌ها تأثیر عمیقی بر اقتصاد و معیشت مردم گذاشته",
        romanization: "tahrimhaa ta'sire amighi bar eqtesaad o ma'ishate mardom gozaashte",
        translation: "制裁は経済と人々の生活に深い影響を与えた",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "حقوق بشر باید فارغ از ملاحظات سیاسی رعایت بشه",
        romanization: "hoghuughe bashar baayad faareghe az molaahezaate siaasi re'aayat beshe",
        translation: "人権は政治的考慮にかかわらず尊重されるべきだ",
        words: ["بشه", "رعایت", "سیاسی", "ملاحظات", "از", "فارغ", "باید", "بشر", "حقوق"],
      },
      {
        type: "dictation",
        phrase: "دموکراسی",
        romanization: "demokraasi",
        translation: "民主主義",
      },
      {
        type: "speak",
        phrase: "دیپلماسی مؤثر می‌تونه بدون توسل به زور منافع ملی رو تأمین کنه",
        romanization: "diplomaasi-ye mo'asser mitune bedune tavassol be zur manaafe'e melli ro ta'min kone",
        translation: "効果的な外交は武力に頼らず国益を確保できる",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c1-literature",
    title: "文学を語る",
    titlePersian: "ادبیات",
    level: "C1",
    steps: [
      {
        type: "tip",
        phrase: "رمان",
        romanization: "romaan",
        translation: "小説",
        tipText: "小説のことです。ペルシア文学は世界最古の文学伝統の一つで、現代小説も盛んです。",
      },
      {
        type: "listen",
        phrase: "سبک نوشتاری صادق هدایت تحت تأثیر سوررئالیسم اروپایی بوده",
        romanization: "sabke neveshtaari-ye Saadegh Hedaayat tahte ta'sire surreaaliseme orupaai bude",
        translation: "サーデグ・ヘダーヤトの文体はヨーロッパのシュルレアリスムの影響を受けている",
      },
      {
        type: "speak",
        phrase: "سبک نوشتاری صادق هدایت تحت تأثیر سوررئالیسم اروپایی بوده",
        romanization: "sabke neveshtaari-ye Saadegh Hedaayat tahte ta'sire surreaaliseme orupaai bude",
        translation: "サーデグ・ヘダーヤトの文体はヨーロッパのシュルレアリスムの影響を受けている",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "شعر فارسی عمق فلسفی و عرفانی خاصی داره",
        romanization: "she're faarsi omghe falsafi o erfaani-ye khaassi daare",
        translation: "ペルシア詩には独特の哲学的・神秘的な深みがある",
      },
      {
        type: "speak",
        phrase: "شعر فارسی عمق فلسفی و عرفانی خاصی داره",
        romanization: "she're faarsi omghe falsafi o erfaani-ye khaassi daare",
        translation: "ペルシア詩には独特の哲学的・神秘的な深みがある",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "نویسنده",
        romanization: "nevisande",
        translation: "作家",
        choices: ["詩人", "作家", "翻訳者", "批評家"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "در این رمان نویسنده به شکل نمادین به بحران هویت می‌پردازه",
        romanization: "dar in romaan nevisande be shekle namadin be bohraane hoviyat mipardaaze",
        translation: "この小説で作家は象徴的にアイデンティティの危機を扱っている",
      },
      {
        type: "speak",
        phrase: "در این رمان نویسنده به شکل نمادین به بحران هویت می‌پردازه",
        romanization: "dar in romaan nevisande be shekle namadin be bohraane hoviyat mipardaaze",
        translation: "この小説で作家は象徴的にアイデンティティの危機を扱っている",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "شعر فارسی عمق فلسفی و عرفانی خاصی داره",
        romanization: "she're faarsi omghe falsafi o erfaani-ye khaassi daare",
        translation: "ペルシア詩には独特の哲学的・神秘的な深みがある",
        words: ["داره", "خاصی", "عرفانی", "و", "فلسفی", "عمق", "فارسی", "شعر"],
      },
      {
        type: "dictation",
        phrase: "نویسنده",
        romanization: "nevisande",
        translation: "作家",
      },
      {
        type: "speak",
        phrase: "ادبیات معاصر ایران بازتابی از تحولات اجتماعی و فرهنگی چند دهه اخیره",
        romanization: "adabiyaate mo'aasere iraan baztaabi az tahavvolaate ejtemaa'i o farhangi-ye chand dahe-ye akhire",
        translation: "現代イラン文学はここ数十年の社会的・文化的変化を反映している",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c1-philosophy",
    title: "哲学的対話",
    titlePersian: "گفتگوی فلسفی",
    level: "C1",
    steps: [
      {
        type: "tip",
        phrase: "هستی",
        romanization: "hasti",
        translation: "存在",
        tipText: "存在についてです。イラン哲学はイスラム思想と古代ペルシアの知恵が融合した豊かな伝統を持ちます。",
      },
      {
        type: "listen",
        phrase: "مسئله هستی و نیستی از دیرباز ذهن فیلسوفان رو به خود مشغول کرده",
        romanization: "mas'ale-ye hasti o nisti az dirbaaz zehne filsufaan ro be khod mashghul karde",
        translation: "存在と無の問題は古来より哲学者たちの心を占めてきた",
      },
      {
        type: "speak",
        phrase: "مسئله هستی و نیستی از دیرباز ذهن فیلسوفان رو به خود مشغول کرده",
        romanization: "mas'ale-ye hasti o nisti az dirbaaz zehne filsufaan ro be khod mashghul karde",
        translation: "存在と無の問題は古来より哲学者たちの心を占めてきた",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "آیا اخلاق امری مطلق است یا نسبی؟",
        romanization: "aayaa akhlaagh amri motlagh ast yaa nesbi?",
        translation: "道徳は絶対的なものか相対的なものか？",
      },
      {
        type: "speak",
        phrase: "آیا اخلاق امری مطلق است یا نسبی؟",
        romanization: "aayaa akhlaagh amri motlagh ast yaa nesbi?",
        translation: "道徳は絶対的なものか相対的なものか？",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "آزادی اراده",
        romanization: "aazaadi-ye eraade",
        translation: "自由意志",
        choices: ["決定論", "自由意志", "道徳律", "合理主義"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "اگر آزادی اراده وجود نداشته باشه مسئولیت اخلاقی بی‌معنا می‌شه",
        romanization: "agar aazaadi-ye eraade vojud nadaashte baashe mas'uliyate akhlaaghi bi-ma'naa mishe",
        translation: "もし自由意志が存在しなければ、道徳的責任は無意味になる",
      },
      {
        type: "speak",
        phrase: "اگر آزادی اراده وجود نداشته باشه مسئولیت اخلاقی بی‌معنا می‌شه",
        romanization: "agar aazaadi-ye eraade vojud nadaashte baashe mas'uliyate akhlaaghi bi-ma'naa mishe",
        translation: "もし自由意志が存在しなければ、道徳的責任は無意味になる",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "آیا اخلاق امری مطلق است یا نسبی؟",
        romanization: "aayaa akhlaagh amri motlagh ast yaa nesbi?",
        translation: "道徳は絶対的なものか相対的なものか？",
        words: ["نسبی؟", "یا", "است", "مطلق", "امری", "اخلاق", "آیا"],
      },
      {
        type: "dictation",
        phrase: "هستی",
        romanization: "hasti",
        translation: "存在",
      },
      {
        type: "speak",
        phrase: "ملاصدرا معتقد بود که هستی دارای مراتب و تشکیک است و حقیقتی واحد با شدت و ضعف",
        romanization: "Mollaa Sadraa mo'taghed bud ke hasti daaraa-ye maraateb o tashkik ast o haghighati vaahed baa sheddat o za'f",
        translation: "ムッラー・サドラーは、存在には段階と強弱があり、一つの実在に強度と微弱があると信じた",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c1-business-strategy",
    title: "ビジネス戦略",
    titlePersian: "استراتژی کسب و کار",
    level: "C1",
    steps: [
      {
        type: "tip",
        phrase: "استراتژی",
        romanization: "estratezhi",
        translation: "戦略",
        tipText: "戦略のことです。ビジネスの文脈で頻出で、イランのスタートアップシーンでも使われます。",
      },
      {
        type: "listen",
        phrase: "تدوین استراتژی بلندمدت برای هر کسب و کاری ضروریه",
        romanization: "tadvin-e estratezhi-ye boland-moddat baraaye har kasb-o-kaari zaruri-ye",
        translation: "あらゆるビジネスにとって長期戦略の策定は不可欠だ",
      },
      {
        type: "speak",
        phrase: "تدوین استراتژی بلندمدت برای هر کسب و کاری ضروریه",
        romanization: "tadvin-e estratezhi-ye boland-moddat baraaye har kasb-o-kaari zaruri-ye",
        translation: "あらゆるビジネスにとって長期戦略の策定は不可欠だ",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "سهام‌داران نگران بازدهی سرمایه‌گذاریشون هستن",
        romanization: "sahaam-daaraan negaraane baazdehi-ye sarmaaye-gozaarishun hastan",
        translation: "株主たちは投資収益率を心配している",
      },
      {
        type: "speak",
        phrase: "سهام‌داران نگران بازدهی سرمایه‌گذاریشون هستن",
        romanization: "sahaam-daaraan negaraane baazdehi-ye sarmaaye-gozaarishun hastan",
        translation: "株主たちは投資収益率を心配している",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "بازاریابی",
        romanization: "baazaar-yaabi",
        translation: "マーケティング",
        choices: ["財務管理", "マーケティング", "人事管理", "品質管理"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "بازاریابی دیجیتال نقش محوری در رشد استارتاپ‌ها ایفا می‌کنه",
        romanization: "baazaar-yaabi-ye dijitaal naghshe mehvari dar roshde estaartaaphaa ifaa mikone",
        translation: "デジタルマーケティングはスタートアップの成長に中心的な役割を果たしている",
      },
      {
        type: "speak",
        phrase: "بازاریابی دیجیتال نقش محوری در رشد استارتاپ‌ها ایفا می‌کنه",
        romanization: "baazaar-yaabi-ye dijitaal naghshe mehvari dar roshde estaartaaphaa ifaa mikone",
        translation: "デジタルマーケティングはスタートアップの成長に中心的な役割を果たしている",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "تدوین استراتژی بلندمدت برای هر کسب و کاری ضروریه",
        romanization: "tadvin-e estratezhi-ye boland-moddat baraaye har kasb-o-kaari zaruri-ye",
        translation: "あらゆるビジネスにとって長期戦略の策定は不可欠だ",
        words: ["ضروریه", "کاری", "کسب و", "هر", "برای", "بلندمدت", "استراتژی", "تدوین"],
      },
      {
        type: "dictation",
        phrase: "استراتژی",
        romanization: "estratezhi",
        translation: "戦略",
      },
      {
        type: "speak",
        phrase: "برای حفظ مزیت رقابتی باید نوآوری مستمر رو در اولویت قرار بدیم",
        romanization: "baraaye hefze maziyate reghaabit baayad now-aavari-ye mostamar ro dar olaviyat gharaar bedim",
        translation: "競争優位を維持するには、継続的なイノベーションを優先すべきだ",
        praiseText: "عالی بود!",
      },
    ],
  },

  // ═══════════════════════ C2 ═══════════════════════

  {
    id: "c2-poetry-culture",
    title: "詩と文化の深層",
    titlePersian: "شعر و فرهنگ",
    level: "C2",
    steps: [
      {
        type: "tip",
        phrase: "حافظ",
        romanization: "Haafez",
        translation: "ハーフェズ（14世紀の大詩人）",
        tipText: "ハーフェズはイラン人の魂です。詩集はほぼ全てのイラン家庭にあります。",
      },
      {
        type: "listen",
        phrase: "حافظ در غزلیاتش با زبان رمزآلود از عشق الهی و زمینی سخن می‌گوید",
        romanization: "Haafez dar ghazaliyaatash baa zabaane ramz-aalud az eshghe elaahi o zamini sokhan migooyad",
        translation: "ハーフェズは抒情詩で暗示的な言葉を使い、神聖な愛と世俗の愛を語る",
      },
      {
        type: "speak",
        phrase: "حافظ در غزلیاتش با زبان رمزآلود از عشق الهی و زمینی سخن می‌گوید",
        romanization: "Haafez dar ghazaliyaatash baa zabaane ramz-aalud az eshghe elaahi o zamini sokhan migooyad",
        translation: "ハーフェズは抒情詩で暗示的な言葉を使い、神聖な愛と世俗の愛を語る",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "مولانا در مثنوی از تمثیل و استعاره برای بیان حقایق عرفانی بهره می‌گیرد",
        romanization: "Mowlaanaa dar Masnavi az tamsil o este'aare baraaye bayaane haghaayghe erfaani bahre migirad",
        translation: "ルーミーは『マスナヴィー』で寓話と隠喩を用いて神秘的な真理を表現する",
      },
      {
        type: "speak",
        phrase: "مولانا در مثنوی از تمثیل و استعاره برای بیان حقایق عرفانی بهره می‌گیرد",
        romanization: "Mowlaanaa dar Masnavi az tamsil o este'aare baraaye bayaane haghaayghe erfaani bahre migirad",
        translation: "ルーミーは『マスナヴィー』で寓話と隠喩を用いて神秘的な真理を表現する",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "استعاره",
        romanization: "este'aare",
        translation: "隠喩（メタファー）",
        choices: ["直喩", "隠喩", "擬人法", "誇張法"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "تمثیل نی‌نامه بازتابی از درد فراق و اشتیاق بازگشت به اصل است",
        romanization: "tamsile Ney-naame baztaabi az darde feraagh o eshtiaaaghe baazgasht be asl ast",
        translation: "葦笛の物語の寓話は、別離の苦しみと根源への回帰への渇望を映し出す",
      },
      {
        type: "speak",
        phrase: "تمثیل نی‌نامه بازتابی از درد فراق و اشتیاق بازگشت به اصل است",
        romanization: "tamsile Ney-naame baztaabi az darde feraagh o eshtiaaaghe baazgasht be asl ast",
        translation: "葦笛の物語の寓話は、別離の苦しみと根源への回帰への渇望を映し出す",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "حافظ در غزلیاتش با زبان رمزآلود سخن می‌گوید",
        romanization: "Haafez dar ghazaliyaatash baa zabaane ramz-aalud sokhan migooyad",
        translation: "ハーフェズは抒情詩で暗示的な言葉を使い語る",
        words: ["می‌گوید", "سخن", "رمزآلود", "زبان", "با", "غزلیاتش", "در", "حافظ"],
      },
      {
        type: "dictation",
        phrase: "استعاره",
        romanization: "este'aare",
        translation: "隠喩",
      },
      {
        type: "speak",
        phrase: "ایرانی‌ها در شب یلدا دیوان حافظ رو فال می‌گیرن و این سنتی هزارساله‌ست که شعر رو با زندگی روزمره پیوند می‌زنه",
        romanization: "iraanihaa dar shabe Yaldaa divaane Haafez ro faal migiran o in sonnati hezaar-saale-st ke she'r ro baa zendegi-ye ruzmare peyvand mizane",
        translation: "イラン人はヤルダーの夜にハーフェズ詩集で占いをする。これは詩と日常を結びつける千年の伝統だ",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c2-rhetoric",
    title: "説得と修辞",
    titlePersian: "فن بلاغت و اقناع",
    level: "C2",
    steps: [
      {
        type: "tip",
        phrase: "بلاغت",
        romanization: "balaaghat",
        translation: "修辞学（レトリック）",
        tipText: "修辞学のことです。ペルシア語の知的伝統で、論証・説得の技術として重視されてきました。",
      },
      {
        type: "listen",
        phrase: "استدلال منطقی بدون پشتوانه واقعی چیزی جز سفسطه نیست",
        romanization: "estedlaale manteghi bedune poshtavaane vaaghe'i chizi joz safsate nist",
        translation: "実質的な裏付けのない論理的推論は詭弁に過ぎない",
      },
      {
        type: "speak",
        phrase: "استدلال منطقی بدون پشتوانه واقعی چیزی جز سفسطه نیست",
        romanization: "estedlaale manteghi bedune poshtavaane vaaghe'i chizi joz safsate nist",
        translation: "実質的な裏付けのない論理的推論は詭弁に過ぎない",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "مغالطه توسل به احساسات یکی از رایج‌ترین خطاهای منطقی در مناظرات است",
        romanization: "moghaalate-ye tavassol be ehsaasaat yeki az raayej-tarin khataahaa-ye manteghi dar monaaze-raat ast",
        translation: "感情に訴える誤謬は討論における最も一般的な論理的誤りの一つだ",
      },
      {
        type: "speak",
        phrase: "مغالطه توسل به احساسات یکی از رایج‌ترین خطاهای منطقی در مناظرات است",
        romanization: "moghaalate-ye tavassol be ehsaasaat yeki az raayej-tarin khataahaa-ye manteghi dar monaaze-raat ast",
        translation: "感情に訴える誤謬は討論における最も一般的な論理的誤りの一つだ",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "مغالطه",
        romanization: "moghaalate",
        translation: "誤謬・詭弁",
        choices: ["論証", "誤謬・詭弁", "仮説", "結論"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "سخنور ماهر با ترکیب استدلال و بیان مؤثر مخاطب رو متقاعد می‌کنه",
        romanization: "sokhanvare maaher baa tarkibe estedlaal o bayaane mo'asser mokhaaatab ro motaghaa'ed mikone",
        translation: "熟練した雄弁家は論証と効果的な表現の組み合わせで聴衆を説得する",
      },
      {
        type: "speak",
        phrase: "سخنور ماهر با ترکیب استدلال و بیان مؤثر مخاطب رو متقاعد می‌کنه",
        romanization: "sokhanvare maaher baa tarkibe estedlaal o bayaane mo'asser mokhaaatab ro motaghaa'ed mikone",
        translation: "熟練した雄弁家は論証と効果的な表現の組み合わせで聴衆を説得する",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "استدلال منطقی بدون پشتوانه واقعی سفسطه نیست",
        romanization: "estedlaale manteghi bedune poshtavaane vaaghe'i safsate nist",
        translation: "実質的な裏付けのない論理的推論は詭弁だ",
        words: ["نیست", "سفسطه", "واقعی", "پشتوانه", "بدون", "منطقی", "استدلال"],
      },
      {
        type: "dictation",
        phrase: "بلاغت",
        romanization: "balaaghat",
        translation: "修辞学",
      },
      {
        type: "speak",
        phrase: "در سنت ادبی فارسی بلاغت نه صرفاً ابزار اقناع بلکه هنری برای زیبا ساختن اندیشه تلقی می‌شده",
        romanization: "dar sonnate adabi-ye faarsi balaaghat na serfan abzaare eghnaa' balke honari baraaye zibaa saakhtan-e andishe tallaghi mishode",
        translation: "ペルシア文学の伝統では修辞学は単なる説得の道具ではなく、思想を美しくする芸術と見なされてきた",
        praiseText: "عالی بود!",
      },
    ],
  },

  {
    id: "c2-identity",
    title: "アイデンティティと帰属",
    titlePersian: "هویت و تعلق",
    level: "C2",
    steps: [
      {
        type: "tip",
        phrase: "هویت",
        romanization: "hoviyat",
        translation: "アイデンティティ",
        tipText: "アイデンティティのことです。移住やグローバル化の中で、「自分は何者か」は現代イラン人の核心的テーマです。",
      },
      {
        type: "listen",
        phrase: "هویت فرهنگی چیزی ایستا نیست بلکه در تعامل مداوم با محیط شکل می‌گیره",
        romanization: "hoviyate farhangi chizi istaa nist balke dar ta'aamole modaavem baa mohit shekl migire",
        translation: "文化的アイデンティティは静的なものではなく、環境との絶え間ない相互作用の中で形成される",
      },
      {
        type: "speak",
        phrase: "هویت فرهنگی چیزی ایستا نیست بلکه در تعامل مداوم با محیط شکل می‌گیره",
        romanization: "hoviyate farhangi chizi istaa nist balke dar ta'aamole modaavem baa mohit shekl migire",
        translation: "文化的アイデンティティは静的なものではなく、環境との絶え間ない相互作用の中で形成される",
        praiseText: "آفرین!",
      },
      {
        type: "listen",
        phrase: "تعلق به سرزمین مادری حتی پس از سال‌ها مهاجرت در ناخودآگاه ریشه داره",
        romanization: "ta'allogh be sarzamine maadari hattaa pas az saalhaa mohaajer-at dar naakhodaagaah rishe daare",
        translation: "母国への帰属意識は長年の移住の後でさえ無意識に根を張っている",
      },
      {
        type: "speak",
        phrase: "تعلق به سرزمین مادری حتی پس از سال‌ها مهاجرت در ناخودآگاه ریشه داره",
        romanization: "ta'allogh be sarzamine maadari hattaa pas az saalhaa mohaajer-at dar naakhodaagaah rishe daare",
        translation: "母国への帰属意識は長年の移住の後でさえ無意識に根を張っている",
        praiseText: "عالی!",
      },
      {
        type: "choose",
        phrase: "مهاجرت",
        romanization: "mohaajerat",
        translation: "移住",
        choices: ["帰国", "移住", "亡命", "旅行"],
        correctChoiceIndex: 1,
      },
      {
        type: "listen",
        phrase: "ایرانیان مهاجر اغلب با دوگانگی هویتی دست و پنجه نرم می‌کنن",
        romanization: "iraaniaane mohaajer aghlab baa dogaanegi-ye hoviyati dast o panje narm mikonan",
        translation: "海外在住イラン人はしばしばアイデンティティの二重性と格闘する",
      },
      {
        type: "speak",
        phrase: "ایرانیان مهاجر اغلب با دوگانگی هویتی دست و پنجه نرم می‌کنن",
        romanization: "iraaniaane mohaajer aghlab baa dogaanegi-ye hoviyati dast o panje narm mikonan",
        translation: "海外在住イラン人はしばしばアイデンティティの二重性と格闘する",
        praiseText: "خیلی خوب!",
      },
      {
        type: "reorder",
        phrase: "هویت فرهنگی چیزی ایستا نیست بلکه در تعامل با محیط شکل می‌گیره",
        romanization: "hoviyate farhangi chizi istaa nist balke dar ta'aamol baa mohit shekl migire",
        translation: "文化的アイデンティティは静的ではなく環境との相互作用で形成される",
        words: ["می‌گیره", "شکل", "محیط", "با", "تعامل", "در", "بلکه", "نیست", "ایستا", "چیزی", "فرهنگی", "هویت"],
      },
      {
        type: "dictation",
        phrase: "هویت",
        romanization: "hoviyat",
        translation: "アイデンティティ",
      },
      {
        type: "speak",
        phrase: "در خانواده‌های چندفرهنگی بچه‌ها گاهی بین دو زبان و دو جهان‌بینی معلق می‌مونن و همین تعلیق خود گنجینه‌ای از تجربه و بینش می‌شه",
        romanization: "dar khaanevaadehaa-ye chand-farhangi bachehaa gaahi beyne do zabaan o do jahaanbini mo'alagh mimoonan o hamin ta'ligh khod ganjine-i az tajrobe o binesh mishe",
        translation: "多文化家庭の子供たちは時に二つの言語と世界観の間で宙吊りになるが、その宙吊りこそが経験と洞察の宝庫となる",
        praiseText: "عالی بود!",
      },
    ],
  },
];

// --- Helper Functions ---

export function getLessonsByLevel(level: CEFRLevel): Lesson[] {
  return GUIDED_LESSONS.filter((l) => l.level === level);
}

export function getLessonById(id: string): Lesson | undefined {
  return GUIDED_LESSONS.find((l) => l.id === id);
}

// --- Progress Management (localStorage) ---

const LESSON_PROGRESS_KEY = "guided-lesson-progress";

export interface LessonProgress {
  lessonId: string;
  completedSteps: number;
  completed: boolean;
  lastDate: string;
  phrasesLearned: number;
}

export function getLessonProgress(): Record<string, LessonProgress> {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(LESSON_PROGRESS_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

export function saveLessonProgress(lessonId: string, completedSteps: number, totalSteps: number): void {
  const all = getLessonProgress();
  const speakSteps = GUIDED_LESSONS.find((l) => l.id === lessonId)
    ?.steps.filter((s) => s.type === "speak" || s.type === "speak-cloze").length ?? 0;

  all[lessonId] = {
    lessonId,
    completedSteps,
    completed: completedSteps >= totalSteps,
    lastDate: new Date().toISOString().split("T")[0],
    phrasesLearned: speakSteps,
  };
  localStorage.setItem(LESSON_PROGRESS_KEY, JSON.stringify(all));
}

export function getNextLesson(level: CEFRLevel): Lesson | undefined {
  const progress = getLessonProgress();
  const lessons = getLessonsByLevel(level);
  return lessons.find((l) => !progress[l.id]?.completed) ?? lessons[0];
}

export function getLevelLessonStats(level: CEFRLevel): { completed: number; total: number } {
  const progress = getLessonProgress();
  const lessons = getLessonsByLevel(level);
  const completed = lessons.filter((l) => progress[l.id]?.completed).length;
  return { completed, total: lessons.length };
}
